create table if not exists public.landing_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event text not null,
  page text,
  source text,
  medium text,
  campaign text,
  content text,
  user_agent text
);

alter table public.landing_events enable row level security;
-- Não é necessário criar policy pública: os inserts são feitos pela função server-side da Vercel usando service role.
